# Generated by Django 4.2.4 on 2023-11-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='users',
            new_name='clients',
        ),
    ]
