# Generated by Django 4.2.4 on 2023-11-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replyed_message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='replyed_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.message'),
        ),
    ]
