# Generated by Django 4.2.4 on 2023-12-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='messages_total',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_reply',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replyed_message',
        ),
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(to='backend.message'),
        ),
    ]
