# Generated by Django 4.2.6 on 2023-11-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_path', models.CharField(blank=True, default='vector/dialog-svgrepo-com.svg', max_length=255, null=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='MessageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'message_states',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=31)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('is_reply', models.BooleanField(blank=True, default=False)),
                ('replyed_message_id', models.BigIntegerField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.chat')),
                ('message_state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.messagestate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.user')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('unread_messages', models.BigIntegerField(blank=True, default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.user')),
            ],
            options={
                'db_table': 'chat_user',
                'unique_together': {('chat', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(through='lab.ChatUser', to='lab.user'),
        ),
    ]
