# Generated by Django 4.2.6 on 2023-11-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_rename_unread_messages_chatuser_read_messages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'chat_states',
            },
        ),
        migrations.AlterField(
            model_name='messagestate',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
