# Generated by Django 4.2.6 on 2023-11-14 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_chatstate_alter_messagestate_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatState',
        ),
        migrations.AlterModelManagers(
            name='chat',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_state',
        ),
        migrations.AddField(
            model_name='chat',
            name='state',
            field=models.IntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.IntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.IntegerField(choices=[(0, 'Deleted'), (1, 'Sent')], default=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.chat'),
        ),
        migrations.DeleteModel(
            name='MessageState',
        ),
    ]
