# Generated by Django 4.2.6 on 2023-11-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_delete_chatstate_alter_chat_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chat',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.IntegerField(choices=[(0, 'Deleted'), (1, 'Sent'), (2, 'Draft'), (3, 'Rejected')], default=1),
        ),
    ]
