# Generated by Django 4.2.6 on 2023-11-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_chat_managers_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
