# Generated by Django 4.2.6 on 2023-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_chat_last_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.IntegerField(choices=[(0, 'Deleted'), (1, 'Sent'), (2, 'Draft'), (3, 'In process'), (4, 'Rejected')], default=1),
        ),
    ]
