# Generated by Django 4.2.6 on 2024-03-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_alter_chat_last_message_time_alter_message_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(null=True, related_name='chats', to='lab.message'),
        ),
    ]
